### ISSUE TITLE
Is it possible to slice the temporary variables only?

### ISSUE THREAD

**Issue by yanshuang16** [srcML/srcSlice#22]
I would like to do a slice of the global variables and the definition of the variable is not in this parsed file, can your tool be implemented?

**Comment by cnewman** [comment]
Yea, this behavior can be implemented. It might already partially be implemented.

I'm currently moving and have no internet besides my phone. I will address this more fully in a couple days once my network is up.

Sorry for the needed delay.

Christian

**Comment by yanshuang16** [comment]
Thank you very much for your reply, if you can, I hope you can tell me the specific steps, how to slice both the global variables and local variables.

**Comment by Hanseltu** [comment]
Hi,

I am also interested in only slicing the global variables. May I ask how can I do this? Thanks!

Best,
Haoxin
