### ISSUE TITLE
How can I use srcSlide for windows or ubuntu?

### ISSUE THREAD

**Issue by PhamAn12** [srcML/srcSlice#25]
Thanks for your awesome tool and open source. However, I find some trouble while building slices after generating srcML. I find the solution in readme file like that : 
To run srcSlice:

First get a srcML version of your code using srcml with position mark up turned on:

srcml [input file] -o [output file] --position

example: srcml file.cpp -o file.cpp.xml

Then take the file you've stored output in and give it to srcSlice:

./srcSlice [input file]

example: ./srcSlice file.cpp.xml

In the first step, it works well. But in the second step ./srcSlice [input file] not work for me. It seems like my terminal realize that ./srcSlice just a path (I did it in ubuntu) 
Is there any other way to use this tool on the window OS.
Many thanks !

**Comment by cnewman** [comment]
Hi @PhamAn12,

Currently, srcSlice is not built for windows. If you have Windows 10, you can try running the tool through the built in Ubuntu emulator (e.g., https://tutorials.ubuntu.com/tutorial/tutorial-ubuntu-on-windows#0). 

If you are already running it using Ubuntu, you should only need to download the executable (at www.srcml.org) and then run it with the srcML file as input (./srcSlice [input file]). You just need to make sure that you are in the same directly are srcSlice when you use that command.

I apologize for the delayed response; these issues go to an old email of mine and I haven't checked it in a while. I need to fix that.

**Comment by PhamAn12** [comment]
Thank you for your reply. I tried with Ubuntu version and it works perfectly. However, I get some new errors when I run this tool . I think I will create a new issue
