### ISSUE TITLE
backward slicing

### ISSUE THREAD

**Issue by mzagane** [srcML/srcSlice#26]
In your paper, you reported that your approach can be extended to compute backward slices. I would like to know if this was done or not yet, and if not, there is a way to do it (backward slicing) using the actual tool with some adapting in the slice profile?
Thank you very much in advance.

**Comment by cnewman** [comment]
Hi @mzagane,

It does not support backward slices at the moment. However, I think someone else has implemented one for srcml

http://mcis.polymtl.ca/~msayagh/TechnicalReports/MCIS-TR-2016-1.pdf

Srcslice could be modified to do backward slices and I'd be happy to support such an endeavor. I don't have time to do it myself currently, however.

**Comment by mzagane** [comment]
@cnewman 
Thank you very much for the help.
