### ISSUE TITLE
can't see the slines field in Old Version 

### ISSUE THREAD

**Issue by PhamAn12** [srcML/srcSlice#28]
I used the old version to check my c program for slicing. But I can't see the slices field in the output . Is that an error ?

**Comment by cnewman** [comment]
If you're referring to slines, then srcSlice doesn't output slines directly.

It outputs 'use' and 'def'. Slines = use U def where U is a union operation. So you just have to combine those together to get slines.

If you did not mean slines, please let me know.

**Comment by PhamAn12** [comment]
That's exactly what I want to ask. Thank you for your answer. 
I tried the input program with variable Struct,  and the results seem to be inaccurate. 
That's my input a.c :
 `#include <stdio.h> 
  
// An example function that takes two parameters 'x' and 'y' 
// as input and returns max of two input numbers 
struct nguoi {
    int ngaysinh;
    int thangsing;
};
int max(int x, int y) 
{ 
    if (x > y) 
      return x; 
    else
      return y; 
} 
  
// main function that doesn't receive any parameter and 
// returns integer. 
int main(void) 
{ 
    int a = 10, b = 20; 
    struct nguoi cc;
    cc.ngaysinh = 1;
    cc.thangsing = 2;
    // Calling above function to find max of 'a' and 'b' 
    int m = max(a, b); 
  
    printf("m is %d", m); 
    return 0; 
} 
`
And the output like that : (At output.cpp, I call TestSlice function in srcSliceToCsv function)
Time is: 0.001034
-------------------------
Variable: n
Slines: {11,12,}
variables dependant on this one: {}
is aliase for: {}
cfuntions: {}
def: {11,}
use: {12,}
-------------------------
-------------------------
Variable: m
Slines: {5,6,7,}
variables dependant on this one: {}
is aliase for: {}
cfuntions: {printf 1,}
def: {5,6,}
use: {7,}
-------------------------
where was i wrong ?

**Comment by cnewman** [comment]
Typically, this happens when you've run srcML without --position turned on.

i.e., srcml --position (input file)

--position turns on line position information in the srcML archive, which srcSlice requires to run correctly.
